from flask_wtf import FlaskForm
from wtforms import StringField, RadioField, SubmitField
from wtforms.validators import DataRequired

class PersonalityChecklistForm(FlaskForm):
    name = StringField('Your Name', validators=[DataRequired()])
    top_passages = StringField('Top 3 Bible Passages', validators=[DataRequired()])
    top_characters = StringField('Top 3 Bible Characters', validators=[DataRequired()])
    encouragement = StringField('Word of Encouragement or Warning', validators=[DataRequired()])
    question1 = RadioField('Do you consider yourself a leader?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question2 = RadioField('Are you more of a thinker than a doer?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question3 = RadioField('Do you value community and fellowship?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question4 = RadioField('Are you willing to sacrifice for others?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question5 = RadioField('Do you seek wisdom and understanding?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question6 = RadioField('Are you a person of action?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question7 = RadioField('Do you enjoy helping others?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question8 = RadioField('Do you prefer to work behind the scenes?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question9 = RadioField('Are you a peacemaker?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question10 = RadioField('Do you have a strong sense of justice?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question11 = RadioField('Do you have a passion for teaching?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question12 = RadioField('Are you a person of prayer?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question13 = RadioField('Do you enjoy studying scripture?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question14 = RadioField('Do you feel called to serve others?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question15 = RadioField('Do you have a heart for missions?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question16 = RadioField('Do you have a gift of hospitality?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question17 = RadioField('Do you have a gift of encouragement?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question18 = RadioField('Do you have a gift of leadership?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question19 = RadioField('Do you have a gift of mercy?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question20 = RadioField('Do you have a gift of giving?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    question21 = RadioField('Do you have a gift of faith?', choices=[('yes', 'Yes'), ('no', 'No')], validators=[DataRequired()])
    submit = SubmitField('Submit')